#ifndef QUERCUS_CHAINPARAMSSEEDS_H
#define QUERCUS_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the quercus network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x9e,0x45,0xdf,0x8b,0x44,0xfa,
};

static const uint8_t chainparams_seed_test[] = {
};
#endif // QUERCUS_CHAINPARAMSSEEDS_H
